In [1]:
from google.colab import drive
drive.mount('/content/drive')
! pip install configargparse
! pip install wandb
! pip install open3d
! pip install lpips

Mounted at /content/drive
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.8 MB 8.1 MB/s 
     |████████████████████████████████| 157 kB 56.1 MB/s 
     |████████████████████████████████| 181 kB 57.1 MB/s 
     |████████████████████████████████| 63 kB 1.7 MB/s 
     |████████████████████████████████| 157 kB 57.5 MB/s 
     |████████████████████████████████| 157 kB 55.9 MB/s 
     |████████████████████████████████| 157 kB 62.9 MB/s 
     |████████████████████████████████| 156 kB 55.3 MB/s 
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8806 sha256=3014bdcb411eecf8cf00d477c0c8cd12c15a493a50e523c56758f0b33d35e043
  Stored in directory: /root/.cache/pip/wheels/3e/31/09/fa59cef12cdcfecc627b3d24273699f390e71828921b2cbba2
Successfully built pathtools
Looking in indexes: http

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 53 kB 1.9 MB/s 


## Run NeRF
WandB apikey: 209f6ac4375563c3d09904b96206a2f5f1d75c24


In [ ]:
! python3 drive/Othercomputers/MacBookPro/NeRF/main.py -c drive/Othercomputers/MacBookPro/NeRF/configs/lego_llff_colab.conf

usage: main.py [-h] [-c CONFIG] [--mesh MESH] [--dataset_path DATASET_PATH]
               [--out_path OUT_PATH]
               [--dataset_type {synthetic,llff,tiny,meshroom,colmap}]
               [--factor FACTOR] [--batch_size BATCH_SIZE] [--shuffle SHUFFLE]
               [--N_samples N_SAMPLES] [--D_c D_C] [--W_c W_C] [--N_f N_F]
               [--lrate LRATE] [--lrate_decay LRATE_DECAY] [--N_iters N_ITERS]
               [--near NEAR] [--far FAR] [--raw_noise_std RAW_NOISE_STD]
               [--dataset_to_gpu] [--colab] [--colab_path COLAB_PATH] [--test]
main.py: error: argument --batch_size: invalid int value: '1024*8'


In [ ]:
! python3 drive/Othercomputers/MacBookPro/nerf-pytorch/run_nerf.py --config drive/Othercomputers/MacBookPro/nerf-pytorch/configs/orchids.txt

## Run Ray tracing a mesh

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Ray-tracing_mesh/ray_tracing_mesh.py -c drive/Othercomputers/MacBookPro/Ray-tracing_mesh/configs/lego_llff.conf

## Surface rendering

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/surface_rendering.py -c drive/Othercomputers/MacBookPro/Rendering/configs/surfrend_colab.conf

Using cuda
['train', 'val', 'test']
tcmalloc: large alloc 1843200000 bytes == 0x8684000 @  0x7f2bdd711001 0x7f2b6cfff1af 0x7f2b6d055c23 0x7f2b6d056a87 0x7f2b6d0f8823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f2bdd30cc87 0x5b621a
Loading train - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_train.npy
	from train_1
tcmalloc: large alloc 1536000000 bytes == 0xd2210000 @  0x7f2bdd70f1e7 0x7f2b6cfff0ce 0x7f2b6d055cf5 0x7f2b6d0fe86d 0x7f2b6d0ff17f 0x7f2b6d0ff2d0 0x4bc4ab 0x7f2b6d040944 0x59371f 0x515244 0x549576 0x593fce 0x548ae9 0x5127f1 0x549e0e 0x4bcb19 0x7f2b6d040944 0x59371f 0x515244 0x549576 0x593fce 0x548ae9 0x51566f 0x549e0e 0x593fce 0x548ae9 0x5127f1 0x549576 0x593fce 0x548ae9 0x5127f1
	Loaded image data (800, 800, 3, 100) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego train
	Change

## Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/radiancemap_colab.conf

# Residual Reflectance

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/resref_colab.conf

# Reflectance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf

# Reflectance Mapping Network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Cluster selector network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_clusterized_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Linear Mapping + Residual MLP

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/mapping_residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Autodecoder

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_autodecoder.py -c drive/Othercomputers/MacBookPro/Rendering/configs/autodecoder_colab.conf

Using cuda
['train', 'val']
tcmalloc: large alloc 1689600000 bytes == 0x9050000 @  0x7f8ef0804001 0x7f8e800f21af 0x7f8e80148c23 0x7f8e80149a87 0x7f8e801eb823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f8ef03ffc87 0x5b621a
Loading train - 100 poses, images (800x800) and lights...
	Changed 1150 items out of 1320 in array of shape (110, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading val - 10 poses, images (800x800) and lights...
	Changed 115 items out of 1320 in array of shape (110, 3, 4)
		From (100, 0, 0) to (109, 2, 3)
Generating rays: 100% 110/110 [00:20<00:00,  5.30pose/s]
tcmalloc: large alloc 3379200000 bytes == 0x7f8d2bd3a000 @  0x7f8ef07e4b6b 0x7f8ef0804379 0x7f8e80ddad57 0x7f8e80dc8bc3 0x7f8eaacbe39f 0x7f8eaacbed10 0x7f8eaacbed64 0x7f8eaacbeeaf 0x7f8eaba4453b 0x7f8eabaa7a52 0x7f8eab1e9047 0x7f8eaba4d5ae 0x7f8eaba4d633 0x7f8eab55e725 0x7f8eab1fb741 0x7f

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_autoencoder.py -c drive/Othercomputers/MacBookPro/Rendering/configs/autodecoder_colab.conf

Using cuda
['train', 'val']
Loading train - 100 poses, images (400x400) and lights...
	Changed 1150 items out of 1320 in array of shape (110, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading val - 10 poses, images (400x400) and lights...
	Changed 115 items out of 1320 in array of shape (110, 3, 4)
		From (100, 0, 0) to (109, 2, 3)
Generating rays: 100% 110/110 [00:05<00:00, 21.71pose/s]
Creating datasets...
	Computing view dirs for train...
tcmalloc: large alloc 1152000000 bytes == 0xc3c92000 @  0x7fe8485f8b6b 0x7fe848618379 0x7fe7d8beed57 0x7fe7d8bdcbc3 0x7fe802ad239f 0x7fe802ad2d10 0x7fe802ad2d64 0x7fe802ad2eaf 0x7fe80385853b 0x7fe8038bba52 0x7fe802ffd047 0x7fe8038615ae 0x7fe803861633 0x7fe80333666c 0x7fe8048aa380 0x7fe8048aab36 0x7fe803372725 0x7fe82a8b8a62 0x593835 0x548c51 0x5127f1 0x549e0e 0x593fce 0x511e2c 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173
	Creating train dataset with rays (torch.Size([16000000, 9])) and images (torch.Size([16000000, 3])) - shuffle True


In [ ]:
import torch
t1 = torch.tensor([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [7, 8, 9]])

unique, inverse = torch.unique(t1, sorted=True, return_inverse=True, dim=0)
perm = torch.arange(inverse.size(0), dtype=inverse.dtype, device=inverse.device)
inverse, perm = inverse.flip([0]), perm.flip([0])
print(unique)
print(inverse)
perm = inverse.new_empty(unique.size(0)).scatter_(0, inverse, perm)
print(perm)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 1, 0, 1, 0])
tensor([0, 1, 4])


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 2])
x.index_fill_(0, index, -1)

cluster_ids = []

tensor([[-1.5066, -0.0317,  0.7404, -0.8176],
        [ 1.2103, -1.2459, -0.9263,  1.2217],
        [-0.0228, -1.3056,  0.7262,  0.2709],
        [-0.6637, -2.1896, -0.3487, -1.2596]])
tensor([[False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True]])
tensor([2, 3, 2, 2])


In [ ]:
X = torch.tensor([[1., 2., 3.], [4., 5., 6.], [1, 2, 3], [4, 5, 6], [7, 8, 9]])
cluster_ids = torch.arange(0, end=5)
cluster_ids = cluster_ids[torch.randperm(cluster_ids.shape[0])]

values = torch.rand((5, 10))
print(values)
col_indices = torch.stack([cluster_ids, cluster_ids+1, cluster_ids+2], dim=0)
print(col_indices)
row_indices = torch.arange(5)
print(values[row_indices, col_indices].T)
print(values[row_indices, col_indices].T.shape)


tensor([[9.2120e-01, 6.5819e-01, 4.7914e-01, 1.4890e-01, 5.2660e-01, 6.3940e-01,
         9.8772e-01, 5.9303e-01, 7.0703e-01, 8.4739e-01],
        [8.5110e-01, 4.0239e-04, 2.8202e-01, 9.1530e-01, 1.8869e-01, 4.2283e-01,
         2.7864e-01, 1.2488e-01, 4.7079e-01, 2.5965e-01],
        [6.6420e-01, 7.4319e-01, 7.1035e-01, 9.8808e-01, 5.7236e-01, 3.9414e-01,
         9.3400e-05, 8.8030e-01, 5.3952e-01, 1.6256e-01],
        [9.9138e-01, 9.0262e-01, 4.6338e-01, 7.3467e-01, 6.1284e-01, 4.9806e-01,
         5.6239e-01, 3.8199e-01, 4.3856e-01, 4.6844e-01],
        [9.2781e-01, 5.1247e-01, 4.5681e-01, 5.4670e-01, 2.5513e-01, 3.3994e-01,
         3.1610e-01, 4.8427e-01, 7.8315e-01, 8.5255e-02]])
tensor([[2, 0, 1, 4, 3],
        [3, 1, 2, 5, 4],
        [4, 2, 3, 6, 5]])
tensor([[4.7914e-01, 1.4890e-01, 5.2660e-01],
        [8.5110e-01, 4.0239e-04, 2.8202e-01],
        [7.4319e-01, 7.1035e-01, 9.8808e-01],
        [6.1284e-01, 4.9806e-01, 5.6239e-01],
        [5.4670e-01, 2.5513e-01, 3.3994e-01]

In [ ]:
import torch
cluster_ids = torch.arange(0,10)

X = torch.rand((10, 3))

def get_x2cluster(X, cluster_ids, num_clusters):
    indices = torch.stack([torch.arange(0,cluster_ids.shape[0]), cluster_ids])
    clusters = torch.sparse_coo_tensor(indices, torch.ones((cluster_ids.shape[0],)), (cluster_ids.shape[0], num_clusters)).to_dense()
    print(clusters.shape)
    x2cluster = torch.linalg.pinv(X) @ clusters  
    print(x2cluster.shape)
    return x2cluster

get_x2cluster(X, cluster_ids, 15)

torch.Size([10, 15])
torch.Size([3, 15])


tensor([[ 0.5149, -0.2283,  0.1728,  0.2384, -0.1754, -0.0055,  0.0579,  0.5413,
         -0.4568, -0.0634,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.4487, -0.1163,  0.1923, -0.0186,  0.7851, -0.2504,  0.1239, -0.3273,
          0.5835, -0.1806,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.1145,  0.5559, -0.1027, -0.0907, -0.4760,  0.4144,  0.0624, -0.0064,
          0.0639,  0.3303,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])