In [1]:
from google.colab import drive
drive.mount('/content/drive')
! pip install configargparse
! pip install wandb
! pip install open3d
! pip install lpips

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Run NeRF
WandB apikey: 209f6ac4375563c3d09904b96206a2f5f1d75c24


In [ ]:
! python3 drive/Othercomputers/MacBookPro/NeRF/main.py -c drive/Othercomputers/MacBookPro/NeRF/configs/lego_llff_colab.conf

usage: main.py [-h] [-c CONFIG] [--mesh MESH] [--dataset_path DATASET_PATH]
               [--out_path OUT_PATH]
               [--dataset_type {synthetic,llff,tiny,meshroom,colmap}]
               [--factor FACTOR] [--batch_size BATCH_SIZE] [--shuffle SHUFFLE]
               [--N_samples N_SAMPLES] [--D_c D_C] [--W_c W_C] [--N_f N_F]
               [--lrate LRATE] [--lrate_decay LRATE_DECAY] [--N_iters N_ITERS]
               [--near NEAR] [--far FAR] [--raw_noise_std RAW_NOISE_STD]
               [--dataset_to_gpu] [--colab] [--colab_path COLAB_PATH] [--test]
main.py: error: argument --batch_size: invalid int value: '1024*8'


In [ ]:
! python3 drive/Othercomputers/MacBookPro/nerf-pytorch/run_nerf.py --config drive/Othercomputers/MacBookPro/nerf-pytorch/configs/orchids.txt

## Run Ray tracing a mesh

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Ray-tracing_mesh/ray_tracing_mesh.py -c drive/Othercomputers/MacBookPro/Ray-tracing_mesh/configs/lego_llff.conf

## Surface rendering

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/surface_rendering.py -c drive/Othercomputers/MacBookPro/Rendering/configs/surfrend_colab.conf

Using cuda
['train', 'val', 'test']
tcmalloc: large alloc 1996800000 bytes == 0x876c000 @  0x7f405df01001 0x7f3fed7b61af 0x7f3fed80cc23 0x7f3fed80da87 0x7f3fed8af823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f405dafcc87 0x5b621a
Loading train - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/microphone/poses_bounds_train.npy
	from train_1
tcmalloc: large alloc 1536000000 bytes == 0xdb43c000 @  0x7f405deff1e7 0x7f3fed7b60ce 0x7f3fed80ccf5 0x7f3fed8b586d 0x7f3fed8b617f 0x7f3fed8b62d0 0x4bc4ab 0x7f3fed7f7944 0x59371f 0x515244 0x549576 0x593fce 0x548ae9 0x5127f1 0x549e0e 0x4bcb19 0x7f3fed7f7944 0x59371f 0x515244 0x549576 0x593fce 0x548ae9 0x51566f 0x549e0e 0x593fce 0x548ae9 0x5127f1 0x549576 0x593fce 0x548ae9 0x5127f1
	Loaded image data (800, 800, 3, 100) [ 800.          800.         1010.71837593]
	Loaded drive/Othercomputers/MacBookPro/microphone t

# Single Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/single_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/single_radiancemap.conf

Using cuda
dataset to:  cpu
['train', 'val', 'test']
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego train
	Changed 12 items out of 72 in array of shape (6, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 5 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_val.npy
	from val_1
	Loaded image data (800, 800, 3, 5) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego val
	Changed 60 items out of 72 in array of shape (6, 3, 4)
		From (1, 0, 0) to (5, 2, 3)
Generating rays: 100% 6/6 [00:01<00:00,  5.69pose/s]
Creating datasets...
	Computing view dirs for train...
	Creating train dataset with rays (torch.Size([640000, 9])) and images (torch.Size([640000, 3])) - shuffle True
	Computing view dirs for val...
	Creating val dataset with rays (torch.Si

# Voxelised Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/voxelised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/voxelised_radiancemap.conf

Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1551360000 bytes == 0x98b8000 @  0x7fa765f27001 0x7fa6f57dc1af 0x7fa6f5832c23 0x7fa6f5833a87 0x7fa6f58d5823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fa765b22c87 0x5b621a
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/microphone/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1010.71837593]
	Loaded drive/Othercomputers/MacBookPro/microphone train
	Changed 12 items out of 1212 in array of shape (101, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/microphone/poses_bounds_val.npy
	from val_1
tcmalloc: large alloc 1536000000 bytes == 0xc1cba000 @  0x7fa765f251e7 0x7fa6f57dc0ce 0x7fa6f5832cf5 0x7fa6f58db86d 0x7fa6f58dc17f 0x7fa6f58dc2d0 0x4bc4ab 0x7f

# Clusterised Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf

Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1551360000 bytes == 0x963a000 @  0x7f8c87c26001 0x7f8c174db1af 0x7f8c17531c23 0x7f8c17532a87 0x7f8c175d4823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f8c87821c87 0x5b621a
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/microphone/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1010.71837593]
	Loaded drive/Othercomputers/MacBookPro/microphone train
	Changed 12 items out of 1212 in array of shape (101, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/microphone/poses_bounds_val.npy
	from val_1
tcmalloc: large alloc 1536000000 bytes == 0xc1a3c000 @  0x7f8c87c241e7 0x7f8c174db0ce 0x7f8c17531cf5 0x7f8c175da86d 0x7f8c175db17f 0x7f8c175db2d0 0x4bc4ab 0x7f

In [ ]:
for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=1 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

# Reflectance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'test']
tcmalloc: large alloc 1551360000 bytes == 0x8aba000 @  0x7effd3adf001 0x7eff633541af 0x7eff633aac23 0x7eff633aba87 0x7eff6344d823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7effd36dac87 0x5b621a
Loading val - 1 poses, images (800x800) and lights...
	Changed 11 items out of 1212 in array of shape (101, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1212 in array of shape (101, 3, 4)
		From (1, 0, 0) to 

In [ ]:
for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf --val_images=1 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['train', 'val']
tcmalloc: large alloc 1551360000 bytes == 0x901c000 @  0x7fc450e36001 0x7fc3e06ab1af 0x7fc3e0701c23 0x7fc3e0702a87 0x7fc3e07a4823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fc450a31c87 0x5b621a
Loading train - 100 poses, images (800x800) and lights...
	Changed 1146 items out of 1212 in array of shape (101, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading val - 1 poses, images (800x800) and lights...
	Changed 12 items out of 1212 in array of shape (101, 3, 4)
		From (100, 0, 0) to (100,

# Reflectance Linear Mapping with Spherical Harmonics Encoding

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf

Traceback (most recent call last):
  File "drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py", line 2, in <module>
    import torch
  File "/usr/local/lib/python3.7/dist-packages/torch/__init__.py", line 201, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.7/dist-packages/torch/__init__.py", line 154, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
KeyboardInterrupt


In [ ]:
for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py --val_images=1 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf

for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['train', 'val']
tcmalloc: large alloc 1551360000 bytes == 0x813c000 @  0x7f22499cd001 0x7f21d92421af 0x7f21d9298c23 0x7f21d9299a87 0x7f21d933b823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f22495c8c87 0x5b621a
Loading train - 100 poses, images (800x800) and lights...
	Changed 1146 items out of 1212 in array of shape (101, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading val - 1 poses, images (800x800) and lights...
	Changed 12 items out of 1212 in array of shape (101, 3, 4)
		From (100, 0, 0) to (100,

# Enhanced Reflectance Network

In [13]:
! python3 drive/Othercomputers/MacBookPro/Rendering/enhanced_reflectance_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/enhanced_reflectance_network.conf

Traceback (most recent call last):
  File "drive/Othercomputers/MacBookPro/Rendering/enhanced_reflectance_network.py", line 6, in <module>
    import open3d as o3d
  File "/usr/local/lib/python3.7/dist-packages/open3d/__init__.py", line 127, in <module>
    import open3d.ml
  File "/usr/local/lib/python3.7/dist-packages/open3d/ml/__init__.py", line 35, in <module>
    from . import datasets
  File "/usr/local/lib/python3.7/dist-packages/open3d/ml/datasets.py", line 34, in <module>
    from open3d._ml3d.datasets import *
  File "/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/datasets/__init__.py", line 4, in <module>
    from .s3dis import S3DIS
  File "/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/datasets/s3dis.py", line 2, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/dist-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/api.py", line 48, in <module>
    fr

# Ablation Studies

## No normals

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf

path ['/content/drive/Othercomputers/MacBookPro/Rendering/ablations', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '../', 'drive/Othercomputers/MacBookPro/', 'drive/Othercomputers/MacBookPro/Rendering/']
Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1551360000 bytes == 0x99ac000 @  0x7f5ce9834001 0x7f5c790e91af 0x7f5c7913fc23 0x7f5c79140a87 0x7f5c791e2823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f5ce942fc87 0x5b621a
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego train
	Changed 12 items out of 1212 in array of shap

# Residual Reflectance

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/resref_colab.conf

# Reflectance Mapping Network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Cluster selector network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_clusterized_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Linear Mapping + Residual MLP

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/mapping_residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Autodecoder

In [16]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_autodecoder.py -c drive/Othercomputers/MacBookPro/Rendering/configs/autodecoder_colab.conf

Using cuda
['val', 'train', 'test']
tcmalloc: large alloc 1612800000 bytes == 0x801e000 @  0x7feabd7ec001 0x7fea4d0a11af 0x7fea4d0f7c23 0x7fea4d0f8a87 0x7fea4d19a823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7feabd3e7c87 0x5b621a
Loading val - 5 poses, images (800x800) and lights...
	Changed 56 items out of 1260 in array of shape (105, 3, 4)
		From (0, 0, 0) to (4, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1260 in array of shape (105, 3, 4)
		From (5, 0, 0) to (104, 2, 3)
Generating rays: 100% 105/105 [00:19<00:00,  5.49pose/s]
tcmalloc: large alloc 3225600000 bytes == 0x128660000 @  0x7feabd7ccb6b 0x7feabd7ec379 0x7fea4dd89d57 0x7fea4dd77bc3 0x7fea77c826af 0x7fea77c83020 0x7fea77c83074 0x7fea77c831bf 0x7fea78a0a82b 0x7fea78a6dd42 0x7fea781ade37 0x7fea78a1389e 0x7fea78a13923 0x7fea78524565 0x7fea781c0531 0x7f

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_autoencoder.py -c drive/Othercomputers/MacBookPro/Rendering/configs/autodecoder_colab.conf

In [ ]:
import torch
t1 = torch.tensor([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [7, 8, 9]])

unique, inverse = torch.unique(t1, sorted=True, return_inverse=True, dim=0)
perm = torch.arange(inverse.size(0), dtype=inverse.dtype, device=inverse.device)
inverse, perm = inverse.flip([0]), perm.flip([0])
print(unique)
print(inverse)
perm = inverse.new_empty(unique.size(0)).scatter_(0, inverse, perm)
print(perm)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 1, 0, 1, 0])
tensor([0, 1, 4])


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 2])
x.index_fill_(0, index, -1)

cluster_ids = []

tensor([[-1.5066, -0.0317,  0.7404, -0.8176],
        [ 1.2103, -1.2459, -0.9263,  1.2217],
        [-0.0228, -1.3056,  0.7262,  0.2709],
        [-0.6637, -2.1896, -0.3487, -1.2596]])
tensor([[False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True]])
tensor([2, 3, 2, 2])


In [ ]:
X = torch.tensor([[1., 2., 3.], [4., 5., 6.], [1, 2, 3], [4, 5, 6], [7, 8, 9]])
cluster_ids = torch.arange(0, end=5)
cluster_ids = cluster_ids[torch.randperm(cluster_ids.shape[0])]

values = torch.rand((5, 10))
print(values)
col_indices = torch.stack([cluster_ids, cluster_ids+1, cluster_ids+2], dim=0)
print(col_indices)
row_indices = torch.arange(5)
print(values[row_indices, col_indices].T)
print(values[row_indices, col_indices].T.shape)


tensor([[9.2120e-01, 6.5819e-01, 4.7914e-01, 1.4890e-01, 5.2660e-01, 6.3940e-01,
         9.8772e-01, 5.9303e-01, 7.0703e-01, 8.4739e-01],
        [8.5110e-01, 4.0239e-04, 2.8202e-01, 9.1530e-01, 1.8869e-01, 4.2283e-01,
         2.7864e-01, 1.2488e-01, 4.7079e-01, 2.5965e-01],
        [6.6420e-01, 7.4319e-01, 7.1035e-01, 9.8808e-01, 5.7236e-01, 3.9414e-01,
         9.3400e-05, 8.8030e-01, 5.3952e-01, 1.6256e-01],
        [9.9138e-01, 9.0262e-01, 4.6338e-01, 7.3467e-01, 6.1284e-01, 4.9806e-01,
         5.6239e-01, 3.8199e-01, 4.3856e-01, 4.6844e-01],
        [9.2781e-01, 5.1247e-01, 4.5681e-01, 5.4670e-01, 2.5513e-01, 3.3994e-01,
         3.1610e-01, 4.8427e-01, 7.8315e-01, 8.5255e-02]])
tensor([[2, 0, 1, 4, 3],
        [3, 1, 2, 5, 4],
        [4, 2, 3, 6, 5]])
tensor([[4.7914e-01, 1.4890e-01, 5.2660e-01],
        [8.5110e-01, 4.0239e-04, 2.8202e-01],
        [7.4319e-01, 7.1035e-01, 9.8808e-01],
        [6.1284e-01, 4.9806e-01, 5.6239e-01],
        [5.4670e-01, 2.5513e-01, 3.3994e-01]

In [ ]:
import torch
cluster_ids = torch.arange(0,10)

X = torch.rand((10, 3))

def get_x2cluster(X, cluster_ids, num_clusters):
    indices = torch.stack([torch.arange(0,cluster_ids.shape[0]), cluster_ids])
    clusters = torch.sparse_coo_tensor(indices, torch.ones((cluster_ids.shape[0],)), (cluster_ids.shape[0], num_clusters)).to_dense()
    print(clusters.shape)
    x2cluster = torch.linalg.pinv(X) @ clusters  
    print(x2cluster.shape)
    return x2cluster

get_x2cluster(X, cluster_ids, 15)

torch.Size([10, 15])
torch.Size([3, 15])


tensor([[ 0.5149, -0.2283,  0.1728,  0.2384, -0.1754, -0.0055,  0.0579,  0.5413,
         -0.4568, -0.0634,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.4487, -0.1163,  0.1923, -0.0186,  0.7851, -0.2504,  0.1239, -0.3273,
          0.5835, -0.1806,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.1145,  0.5559, -0.1027, -0.0907, -0.4760,  0.4144,  0.0624, -0.0064,
          0.0639,  0.3303,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])