In [10]:
from google.colab import drive
drive.mount('/content/drive')
! pip install configargparse
! pip install wandb
! pip install open3d
! pip install lpips
! pip install nvidia-ml-py3
! pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
! pip install torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
! pip install torch-cluster -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
! pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
! pip install torch-geometric

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.12.1+cu113.html
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.12.1+cu113.html
Looking in indexes: https://pypi.org/simple,

## Run NeRF
WandB apikey: 209f6ac4375563c3d09904b96206a2f5f1d75c24


In [ ]:
! python3 drive/Othercomputers/MacBookPro/NeRF/main.py -c drive/Othercomputers/MacBookPro/NeRF/configs/lego_llff_colab.conf

usage: main.py [-h] [-c CONFIG] [--mesh MESH] [--dataset_path DATASET_PATH]
               [--out_path OUT_PATH]
               [--dataset_type {synthetic,llff,tiny,meshroom,colmap}]
               [--factor FACTOR] [--batch_size BATCH_SIZE] [--shuffle SHUFFLE]
               [--N_samples N_SAMPLES] [--D_c D_C] [--W_c W_C] [--N_f N_F]
               [--lrate LRATE] [--lrate_decay LRATE_DECAY] [--N_iters N_ITERS]
               [--near NEAR] [--far FAR] [--raw_noise_std RAW_NOISE_STD]
               [--dataset_to_gpu] [--colab] [--colab_path COLAB_PATH] [--test]
main.py: error: argument --batch_size: invalid int value: '1024*8'


In [ ]:
! python3 drive/Othercomputers/MacBookPro/nerf-pytorch/run_nerf.py --config drive/Othercomputers/MacBookPro/nerf-pytorch/configs/orchids.txt

## Run Ray tracing a mesh

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Ray-tracing_mesh/ray_tracing_mesh.py -c drive/Othercomputers/MacBookPro/Ray-tracing_mesh/configs/lego_llff.conf

## Surface rendering

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/surface_rendering.py -c drive/Othercomputers/MacBookPro/Rendering/configs/surfrend_colab.conf

Using cuda
['train', 'val', 'test']
tcmalloc: large alloc 1551360000 bytes == 0x8764000 @  0x7ffb0a176001 0x7ffa99a2b1af 0x7ffa99a81c23 0x7ffa99a82a87 0x7ffa99b24823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7ffb09d71c87 0x5b621a
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1238.06948234]
	Loaded drive/Othercomputers/MacBookPro/drums train
	Changed 12 items out of 1212 in array of shape (101, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_val.npy
	from val_1
tcmalloc: large alloc 1536000000 bytes == 0xc0b66000 @  0x7ffb0a1741e7 0x7ffa99a2b0ce 0x7ffa99a81cf5 0x7ffa99b2a86d 0x7ffa99b2b17f 0x7ffa99b2b2d0 0x4bc4ab 0x7ffa99a6c944 0x59371f 0x515244 0x5

# Single Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/single_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/single_radiancemap.conf

Using cuda
dataset to:  cpu
['train', 'val', 'test']
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego train
	Changed 12 items out of 72 in array of shape (6, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 5 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_val.npy
	from val_1
	Loaded image data (800, 800, 3, 5) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego val
	Changed 60 items out of 72 in array of shape (6, 3, 4)
		From (1, 0, 0) to (5, 2, 3)
Generating rays: 100% 6/6 [00:01<00:00,  5.69pose/s]
Creating datasets...
	Computing view dirs for train...
	Creating train dataset with rays (torch.Size([640000, 9])) and images (torch.Size([640000, 3])) - shuffle True
	Computing view dirs for val...
	Creating val dataset with rays (torch.Si

# Voxelised Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/voxelised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/voxelised_radiancemap.conf

Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x8736000 @  0x7f2b0bb0b001 0x7f2a9b3c01af 0x7f2a9b416c23 0x7f2a9b417a87 0x7f2a9b4b9823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f2b0b706c87 0x5b621a
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_train.npy
	from train_1
img files ['drive/Othercomputers/MacBookPro/lego/train_1/r_0.png']
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego train
	Changed 12 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_val.npy
	from val_1
img files ['drive/Othercomputers/MacBookPro/lego/val_1/r_100.png']
	Loaded image data (800, 800, 3, 1) [ 800.   

# Clusterised Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf

Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x86b2000 @  0x7f89fc0a0001 0x7f898b9551af 0x7f898b9abc23 0x7f898b9aca87 0x7f898ba4e823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f89fbc9bc87 0x5b621a
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego train
	Changed 12 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_val.npy
	from val_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego val
	Changed 12 items out of 1224 in array of shape (1

In [ ]:
for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

Using cuda
dataset to:  cpu
['val', 'train', 'relighting']
tcmalloc: large alloc 3102720000 bytes == 0x9950000 @  0x7f1126b96001 0x7f10b644b1af 0x7f10b64a1c23 0x7f10b64a2a87 0x7f10b6544823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f1126791c87 0x5b621a
Loading val - 2 poses and images (800x800)...
	Changed 23 items out of 2424 in array of shape (202, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses and images (800x800)...
	Changed 1151 items out of 2424 in array of shape (202, 3, 4)
		From (2, 0, 0) to (101, 2, 3)
Loading relighting - 100 poses and images (800x800)...
	Changed 1140 items out of 2424 in array of shape (202, 3, 4)
		From (102, 0, 0) to (201, 2, 3)
Generating rays: 100% 202/202 [00:36<00:00,  5.47pose/s]
tcmalloc: large alloc 6205440000 bytes == 0x7f0e7a3f4000 @  0x7f1126b76b6b 0x7f1126b96379 0x7f10b7133d57 0x7f10b7121bc3 0x7f10e1

# Reflectance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x8fa8000 @  0x7f0f3155b001 0x7f0ec0dd01af 0x7f0ec0e26c23 0x7f0ec0e27a87 0x7f0ec0ec9823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f0f31156c87 0x5b621a
Loading val - 2 poses, images (800x800) and lights...
	Changed 22 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1224 in array of shape (102, 3, 4)
		From (2, 0, 0) to 

In [ ]:
for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'test']
Traceback (most recent call last):
  File "drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py", line 119, in <module>
    dataset = data.NeRFDataset(args)
  File "drive/Othercomputers/MacBookPro/utils/data.py", line 437, in __init__
    load_light=args.load_light)
  File "drive/Othercomputers/MacBookPro/utils/data.py", line 667, in load_synthetic
    imgs_size, num_images = get_images_size(basedir, subdirs, factor=factor)
  File "drive/Othercomputers/MacBookPro/utils/data.py", line 125, in get_images_size
    files_list = [f for f in os.listdir(os.path.join(basedir, subdir)) 
KeyboardInte

# Reflectance Linear Mapping with Spherical Harmonics Encoding

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf

Traceback (most recent call last):
  File "drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py", line 6, in <module>
    import visualization as v
  File "/content/drive/Othercomputers/MacBookPro/Rendering/visualization.py", line 11, in <module>
    from utils import utils
  File "drive/Othercomputers/MacBookPro/utils/utils.py", line 12, in <module>
    nvidia_smi.nvmlInit()
  File "/usr/local/lib/python3.7/dist-packages/pynvml.py", line 615, in nvmlInit
    _nvmlCheckReturn(ret)
  File "/usr/local/lib/python3.7/dist-packages/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_DriverNotLoaded: Driver Not Loaded


In [ ]:
for (kmeans_tol, num_clusters, batch_size) in [(2.0, 512, 100_000), (5.0, 5_000, 100_000), (5.0, 7_000, 100_000), (5.0, 25_000, 40_000), (10.0, 50_000, 20_000)]: #, (5.0, 10_000, 100_000)
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --train_images=100 --val_images=2 --batch_size=$batch_size
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --train_images=2 --val_images=100 --only_eval --batch_size=$batch_size

Using cuda
['val', 'train', 'test']
tcmalloc: large alloc 1566720000 bytes == 0xa02a000 @  0x7f8ed4ed9001 0x7f8e6478e1af 0x7f8e647e4c23 0x7f8e647e5a87 0x7f8e64887823 0x58f62c 0x5105e2 0x5b4ee6 0x58ff2e 0x50d482 0x4bac0a 0x538786 0x5909f6 0x510946 0x5b4ee6 0x6005a3 0x607796 0x60785c 0x60a436 0x64db82 0x64dd2e 0x7f8ed4ad4c87 0x5b636a
Loading val - 2 poses, images (800x800) and lights...
	Changed 22 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1224 in array of shape (102, 3, 4)
		From (2, 0, 0) to (101, 2, 3)
Generating rays: 100% 102/102 [00:18<00:00,  5.40pose/s]
tcmalloc: large alloc 3133440000 bytes == 0x122296000 @  0x7f8ed4eb9b6b 0x7f8ed4ed9379 0x7f8e65476d57 0x7f8e65464bc3 0x7f8e8f36f6af 0x7f8e8f370020 0x7f8e8f370074 0x7f8e8f3701bf 0x7f8e900f782b 0x7f8e9015ad42 0x7f8e8f89ae37 0x7f8e9010089e 0x7f8e90100923 0x7f8e8fc11565 0x7f8e8f8ad531 0x7f8e902461a3 0x7f8e8fd1885c 0

# Clusterised Reflectance with MLP and SH Encoding

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_MLP_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x87f4000 @  0x7f61908d5001 0x7f612018a1af 0x7f61201e0c23 0x7f61201e1a87 0x7f6120283823 0x58eb9c 0x51b4e6 0x5b41c5 0x58f49e 0x51837f 0x4ba70a 0x537e46 0x58ff66 0x51b7fd 0x5b41c5 0x604133 0x606e06 0x606ecc 0x609aa6 0x64d332 0x64d4de 0x7f61904d0c87 0x5b561a
Loading val - 2 poses, images (800x800) and lights...
	Changed 22 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1224 in array of shape (102, 3, 4)
		From (2, 0, 0) to (101, 2, 3)
Generating rays

In [ ]:
for scene in ["lego", "microphone", "drums"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}_light/{scene}_aligned.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}_light"
    out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/reflectance_{scene}_relighting_sphharm"
    checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/reflectance_{scene}_perfectmesh"
    
    for (kmeans_tol, num_clusters) in [(2e-00, 512)]:#, (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm_relighting.conf --val_images=2 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

    '''for (kmeans_tol, num_clusters) in [(2e-00, 512)]:#, (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm_relighting.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path'''

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'relighting']
tcmalloc: large alloc 1582080000 bytes == 0x8ed2000 @  0x7f906cb25001 0x7f8ffc39a1af 0x7f8ffc3f0c23 0x7f8ffc3f1a87 0x7f8ffc493823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f906c720c87 0x5b621a
Loading val - 2 poses, images (800x800) and lights...
	Changed 23 items out of 1236 in array of shape (103, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 1 poses, images (800x800) and lights...
	Changed 12 items out of 1236 in array of shape (103, 3, 4)
		From (2, 0, 0) t

In [ ]:
for scene in ["lego", "microphone", "drums"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}_light/{scene}_aligned.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}_light"
    out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/reflectance_{scene}_perfectmesh"
    checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/reflectance_{scene}_perfectmesh"
    
    for (kmeans_tol, num_clusters) in [(2e-00, 512)]:#, (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

    for (kmeans_tol, num_clusters) in [(2e-00, 512)]:#, (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train']
tcmalloc: large alloc 1566720000 bytes == 0x8fbc000 @  0x7fa419282001 0x7fa3a8af71af 0x7fa3a8b4dc23 0x7fa3a8b4ea87 0x7fa3a8bf0823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fa418e7dc87 0x5b621a
Loading val - 2 poses, images (800x800) and lights...
	Changed 23 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1151 items out of 1224 in array of shape (102, 3, 4)
		From (2, 0, 0) to (101, 2,

# Enhanced Reflectance Network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/enhanced_reflectance_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/enhanced_reflectance_network.conf

Using cuda
dataset to:  cpu
['val', 'train', 'test']
tcmalloc: large alloc 1689600000 bytes == 0x9daa000 @  0x7f76e7e47001 0x7f76776fc1af 0x7f7677752c23 0x7f7677753a87 0x7f76777f5823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f76e7a42c87 0x5b621a
Loading val - 10 poses, images (800x800) and lights...
	Changed 113 items out of 1320 in array of shape (110, 3, 4)
		From (0, 0, 0) to (9, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1320 in array of shape (110, 3, 4)
		From (10, 0, 0) to (109, 2, 3)
Generating rays: 100% 110/110 [00:19<00:00,  5.51pose/s]
tcmalloc: large alloc 3379200000 bytes == 0x7f7521378000 @  0x7f76e7e27b6b 0x7f76e7e47379 0x7f76783e4d57 0x7f76783d2bc3 0x7f76a22dd6af 0x7f76a22de020 0x7f76a22de074 0x7f76a22de1bf 0x7f76a306582b 0x7f76a30c8d42 0x7f76a2808e37 0x7f76a306e89e 0x7f76a306e923 0x7f76a2b7f

# Ablation Studies

## No normals

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf

path ['/content/drive/Othercomputers/MacBookPro/Rendering/ablations', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '../', 'drive/Othercomputers/MacBookPro/', 'drive/Othercomputers/MacBookPro/Rendering/']
Traceback (most recent call last):
  File "drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py", line 98, in <module>
    import utils.data as data
  File "drive/Othercomputers/MacBookPro/utils/data.py", line 9, in <module>
    import cv2, imageio
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
Key

In [ ]:
for scene in ["drums"]:#, "lego", "microphone"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}/{scene}_aligned2colmap.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}"
    out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/clusterised_radiance_nonormals_{scene}"
    checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/clusterised_radiance_nonormals_{scene}"
    
    for (kmeans_tol, num_clusters) in [(5e-01, 64)]:#[(2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path
        ! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

path ['/content/drive/Othercomputers/MacBookPro/Rendering/ablations', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '../', 'drive/Othercomputers/MacBookPro/', 'drive/Othercomputers/MacBookPro/Rendering/']
Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x8742000 @  0x7f8c6ee60001 0x7f8bfe7151af 0x7f8bfe76bc23 0x7f8bfe76ca87 0x7f8bfe80e823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f8c6ea5bc87 0x5b621a
Loading train - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_train.npy
	from train_1
tcmalloc: large alloc 1536000000 bytes == 0xc19ea000 @  0x7f8c6ee5e1e7 0x7f8bfe7150ce 0x7f8bfe76bcf5 0x7f8bfe81486d 0x7f8bfe81517f 0x7f8bfe8152d0 0x4bc4ab 0x7f8bfe756944 0x59

## No view dirs

In [ ]:
for scene in ["drums"]:#, "lego", "microphone"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}/{scene}_aligned2colmap.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}"
    out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/clusterised_radiance_noviewdirs_{scene}"
    checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/clusterised_radiance_noviewdirs_{scene}"
    
    for (kmeans_tol, num_clusters) in [(5e-01, 64)]:#, (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_noviewdirs.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path
        ! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_noviewdirs.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

path ['/content/drive/Othercomputers/MacBookPro/Rendering/ablations', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '../', 'drive/Othercomputers/MacBookPro/', 'drive/Othercomputers/MacBookPro/Rendering/']
Using cuda
only eval? False
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x84fc000 @  0x7f3901455001 0x7f3890d0a1af 0x7f3890d60c23 0x7f3890d61a87 0x7f3890e03823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f3901050c87 0x5b621a
Loading train - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_train.npy
	from train_1
tcmalloc: large alloc 1536000000 bytes == 0xc17a4000 @  0x7f39014531e7 0x7f3890d0a0ce 0x7f3890d60cf5 0x7f3890e0986d 0x7f3890e0a17f 0x7f3890e0a2d0 0x4bc4ab 0x

## No Positional Encoding & 3 freq. Pos. Enc

In [ ]:
for scene in ["drums"]:#, "lego", "microphone"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}/{scene}_aligned2colmap.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}"
        
    for encoding_freqs in [6]:
        out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/clusterised_radiance_{scene}/{encoding_freqs}freqs"
        checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/clusterised_radiance_{scene}/{encoding_freqs}freqs"
        
        !python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=2 --train_images=100 --encoding_freqs=$encoding_freqs --out_path=$out_path --checkpoint_path=$checkpoint_path --dataset_path=$dataset_path --mesh_path=$mesh_path
        !python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --encoding_freqs=$encoding_freqs --out_path=$out_path --checkpoint_path=$checkpoint_path --dataset_path=$dataset_path --mesh_path=$mesh_path

Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x838a000 @  0x7fed7e196001 0x7fed0da4b1af 0x7fed0daa1c23 0x7fed0daa2a87 0x7fed0db44823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fed7dd91c87 0x5b621a
Loading train - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_train.npy
	from train_1
tcmalloc: large alloc 1536000000 bytes == 0xc1632000 @  0x7fed7e1941e7 0x7fed0da4b0ce 0x7fed0daa1cf5 0x7fed0db4a86d 0x7fed0db4b17f 0x7fed0db4b2d0 0x4bc4ab 0x7fed0da8c944 0x59371f 0x515244 0x549576 0x593fce 0x548ae9 0x5127f1 0x549e0e 0x4bcb19 0x7fed0da8c944 0x59371f 0x515244 0x549576 0x593fce 0x548ae9 0x51566f 0x549e0e 0x593fce 0x548ae9 0x5127f1 0x549576 0x593fce 0x548ae9 0x5127f1
	Loaded image data (800, 800, 3, 100) [ 800.          800.         1238.06948234]
	Loaded drive/Othercomputers/MacBookPro/

## No Spherical Harmonics, 1, 2, 3, 4, 5 degree views

In [ ]:
for scene in ["drums"]:#, "lego", "microphone"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}_light/drums_aligned.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}_light"
    
    for deg_view in [-1, 1, 3, 5]:
        out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/reflectance_{scene}_light_sphharm/{deg_view}degrees_precise"
        checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/reflectance_{scene}_light_sphharm/{deg_view}degrees_precise"
    
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=2 --train_images=100 --test_images=0 --deg_view=$deg_view --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=100 --train_images=1 --test_images=0 --deg_view=$deg_view --only_eval --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x9334000 @  0x7f60d9d96001 0x7f606960b1af 0x7f6069661c23 0x7f6069662a87 0x7f6069704823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f60d9991c87 0x5b621a
Loading val - 2 poses, images (800x800) and lights...
	Changed 24 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1224 in array of shape (102, 3, 4)
		From (2, 0, 0) to 

# Self-attention Clusterised Mappings

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_selfattention.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_selfattention.conf

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x8314000 @  0x7f22d0ac5001 0x7f226033a1af 0x7f2260390c23 0x7f2260391a87 0x7f2260433823 0x58eb9c 0x51b4e6 0x5b41c5 0x58f49e 0x51837f 0x4ba70a 0x537e46 0x58ff66 0x51b7fd 0x5b41c5 0x604133 0x606e06 0x606ecc 0x609aa6 0x64d332 0x64d4de 0x7f22d06c0c87 0x5b561a
Loading val - 2 poses, images (800x800) and lights...
	Changed 22 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1224 in array of shape (102, 3, 4)
		From (2, 0, 0) to (101, 2, 3)
Generating rays

In [ ]:
import torch
mat1 = torch.arange(0, 16).reshape((1, 4, 4))
mat2 = torch.arange(0, 48).reshape((4, 4, 3))

print(mat1)
print(mat2)
result = mat1@mat2
print(result.shape)
print(result)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]])
torch.Size([4, 4, 3])
tensor([[[  42,   48,   54],
         [ 114,  136,  158],
         [ 186,  224,  262],
         [ 258,  312,  366]],

        [[ 114,  120,  126],
         [ 378,  400,  422],
         [ 642,  680,  718],
         [ 906,  960, 1014]],

        [[ 186,  192,  198],
         [ 642,  664,  686],
         [1098, 1136, 1174],
         [1554, 1608, 1662]],

        [[ 258,  264,  270],
         [ 906,  928,  950],
         [1554, 1592, 1630],
         [2202, 2256, 2310]]])


# Residual Reflectance

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/resref_colab.conf

# Reflectance Mapping Network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Cluster selector network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_clusterized_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Linear Mapping + Residual MLP

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/mapping_residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Autodecoder

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_autodecoder.py -c drive/Othercomputers/MacBookPro/Rendering/configs/autodecoder_colab.conf

Using cuda
['val', 'train', 'test']
tcmalloc: large alloc 1612800000 bytes == 0x9a6a000 @  0x7f8b4657d001 0x7f8ad5e321af 0x7f8ad5e88c23 0x7f8ad5e89a87 0x7f8ad5f2b823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f8b46178c87 0x5b621a
Loading val - 5 poses, images (800x800) and lights...
	Changed 56 items out of 1260 in array of shape (105, 3, 4)
		From (0, 0, 0) to (4, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1260 in array of shape (105, 3, 4)
		From (5, 0, 0) to (104, 2, 3)
Generating rays: 100% 105/105 [00:20<00:00,  5.05pose/s]
tcmalloc: large alloc 3225600000 bytes == 0x12a0ac000 @  0x7f8b4655db6b 0x7f8b4657d379 0x7f8ad6b1ad57 0x7f8ad6b08bc3 0x7f8b00a136af 0x7f8b00a14020 0x7f8b00a14074 0x7f8b00a141bf 0x7f8b0179b82b 0x7f8b017fed42 0x7f8b00f3ee37 0x7f8b017a489e 0x7f8b017a4923 0x7f8b012b5565 0x7f8b00f51531 0x7f

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_autoencoder.py -c drive/Othercomputers/MacBookPro/Rendering/configs/autodecoder_colab.conf

In [ ]:
import torch
t1 = torch.tensor([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [7, 8, 9]])

unique, inverse = torch.unique(t1, sorted=True, return_inverse=True, dim=0)
perm = torch.arange(inverse.size(0), dtype=inverse.dtype, device=inverse.device)
inverse, perm = inverse.flip([0]), perm.flip([0])
print(unique)
print(inverse)
perm = inverse.new_empty(unique.size(0)).scatter_(0, inverse, perm)
print(perm)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 1, 0, 1, 0])
tensor([0, 1, 4])


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 2])
x.index_fill_(0, index, -1)

cluster_ids = []

tensor([[-1.5066, -0.0317,  0.7404, -0.8176],
        [ 1.2103, -1.2459, -0.9263,  1.2217],
        [-0.0228, -1.3056,  0.7262,  0.2709],
        [-0.6637, -2.1896, -0.3487, -1.2596]])
tensor([[False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True]])
tensor([2, 3, 2, 2])


In [ ]:
X = torch.tensor([[1., 2., 3.], [4., 5., 6.], [1, 2, 3], [4, 5, 6], [7, 8, 9]])
cluster_ids = torch.arange(0, end=5)
cluster_ids = cluster_ids[torch.randperm(cluster_ids.shape[0])]

values = torch.rand((5, 10))
print(values)
col_indices = torch.stack([cluster_ids, cluster_ids+1, cluster_ids+2], dim=0)
print(col_indices)
row_indices = torch.arange(5)
print(values[row_indices, col_indices].T)
print(values[row_indices, col_indices].T.shape)


tensor([[9.2120e-01, 6.5819e-01, 4.7914e-01, 1.4890e-01, 5.2660e-01, 6.3940e-01,
         9.8772e-01, 5.9303e-01, 7.0703e-01, 8.4739e-01],
        [8.5110e-01, 4.0239e-04, 2.8202e-01, 9.1530e-01, 1.8869e-01, 4.2283e-01,
         2.7864e-01, 1.2488e-01, 4.7079e-01, 2.5965e-01],
        [6.6420e-01, 7.4319e-01, 7.1035e-01, 9.8808e-01, 5.7236e-01, 3.9414e-01,
         9.3400e-05, 8.8030e-01, 5.3952e-01, 1.6256e-01],
        [9.9138e-01, 9.0262e-01, 4.6338e-01, 7.3467e-01, 6.1284e-01, 4.9806e-01,
         5.6239e-01, 3.8199e-01, 4.3856e-01, 4.6844e-01],
        [9.2781e-01, 5.1247e-01, 4.5681e-01, 5.4670e-01, 2.5513e-01, 3.3994e-01,
         3.1610e-01, 4.8427e-01, 7.8315e-01, 8.5255e-02]])
tensor([[2, 0, 1, 4, 3],
        [3, 1, 2, 5, 4],
        [4, 2, 3, 6, 5]])
tensor([[4.7914e-01, 1.4890e-01, 5.2660e-01],
        [8.5110e-01, 4.0239e-04, 2.8202e-01],
        [7.4319e-01, 7.1035e-01, 9.8808e-01],
        [6.1284e-01, 4.9806e-01, 5.6239e-01],
        [5.4670e-01, 2.5513e-01, 3.3994e-01]

In [ ]:
import torch
cluster_ids = torch.arange(0,10)

X = torch.rand((10, 3))

def get_x2cluster(X, cluster_ids, num_clusters):
    indices = torch.stack([torch.arange(0,cluster_ids.shape[0]), cluster_ids])
    clusters = torch.sparse_coo_tensor(indices, torch.ones((cluster_ids.shape[0],)), (cluster_ids.shape[0], num_clusters)).to_dense()
    print(clusters.shape)
    x2cluster = torch.linalg.pinv(X) @ clusters  
    print(x2cluster.shape)
    return x2cluster

get_x2cluster(X, cluster_ids, 15)

torch.Size([10, 15])
torch.Size([3, 15])


tensor([[ 0.5149, -0.2283,  0.1728,  0.2384, -0.1754, -0.0055,  0.0579,  0.5413,
         -0.4568, -0.0634,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.4487, -0.1163,  0.1923, -0.0186,  0.7851, -0.2504,  0.1239, -0.3273,
          0.5835, -0.1806,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.1145,  0.5559, -0.1027, -0.0907, -0.4760,  0.4144,  0.0624, -0.0064,
          0.0639,  0.3303,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])