In [3]:
from google.colab import drive
drive.mount('/content/drive')
! pip install configargparse
! pip install wandb
! pip install open3d
! pip install lpips

Mounted at /content/drive
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.8 MB 7.1 MB/s 
     |████████████████████████████████| 157 kB 76.5 MB/s 
     |████████████████████████████████| 181 kB 74.1 MB/s 
     |████████████████████████████████| 63 kB 2.1 MB/s 
     |████████████████████████████████| 157 kB 96.4 MB/s 
     |████████████████████████████████| 157 kB 88.0 MB/s 
     |████████████████████████████████| 157 kB 87.2 MB/s 
     |████████████████████████████████| 157 kB 85.5 MB/s 
     |████████████████████████████████| 156 kB 85.4 MB/s 
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8806 sha256=70bb1f617ea73a2b09e6ef6e2699e04d712a89b9eb36db583359a317d50a4003
  Stored in directory: /root/.cache/pip/wheels/3e/31/09/fa59cef12cdcfecc627b3d24273699f390e71828921b2c

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 53 kB 2.2 MB/s 


## Run NeRF
WandB apikey: 209f6ac4375563c3d09904b96206a2f5f1d75c24


In [ ]:
! python3 drive/Othercomputers/MacBookPro/NeRF/main.py -c drive/Othercomputers/MacBookPro/NeRF/configs/lego_llff_colab.conf

usage: main.py [-h] [-c CONFIG] [--mesh MESH] [--dataset_path DATASET_PATH]
               [--out_path OUT_PATH]
               [--dataset_type {synthetic,llff,tiny,meshroom,colmap}]
               [--factor FACTOR] [--batch_size BATCH_SIZE] [--shuffle SHUFFLE]
               [--N_samples N_SAMPLES] [--D_c D_C] [--W_c W_C] [--N_f N_F]
               [--lrate LRATE] [--lrate_decay LRATE_DECAY] [--N_iters N_ITERS]
               [--near NEAR] [--far FAR] [--raw_noise_std RAW_NOISE_STD]
               [--dataset_to_gpu] [--colab] [--colab_path COLAB_PATH] [--test]
main.py: error: argument --batch_size: invalid int value: '1024*8'


In [ ]:
! python3 drive/Othercomputers/MacBookPro/nerf-pytorch/run_nerf.py --config drive/Othercomputers/MacBookPro/nerf-pytorch/configs/orchids.txt

## Run Ray tracing a mesh

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Ray-tracing_mesh/ray_tracing_mesh.py -c drive/Othercomputers/MacBookPro/Ray-tracing_mesh/configs/lego_llff.conf

## Surface rendering

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/surface_rendering.py -c drive/Othercomputers/MacBookPro/Rendering/configs/surfrend_colab.conf

Using cuda
['train', 'val', 'test']
tcmalloc: large alloc 1551360000 bytes == 0x8764000 @  0x7ffb0a176001 0x7ffa99a2b1af 0x7ffa99a81c23 0x7ffa99a82a87 0x7ffa99b24823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7ffb09d71c87 0x5b621a
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1238.06948234]
	Loaded drive/Othercomputers/MacBookPro/drums train
	Changed 12 items out of 1212 in array of shape (101, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_val.npy
	from val_1
tcmalloc: large alloc 1536000000 bytes == 0xc0b66000 @  0x7ffb0a1741e7 0x7ffa99a2b0ce 0x7ffa99a81cf5 0x7ffa99b2a86d 0x7ffa99b2b17f 0x7ffa99b2b2d0 0x4bc4ab 0x7ffa99a6c944 0x59371f 0x515244 0x5

# Single Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/single_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/single_radiancemap.conf

Using cuda
dataset to:  cpu
['train', 'val', 'test']
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego train
	Changed 12 items out of 72 in array of shape (6, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 5 images...
Fileposes:  drive/Othercomputers/MacBookPro/lego/poses_bounds_val.npy
	from val_1
	Loaded image data (800, 800, 3, 5) [ 800.          800.         1094.61880067]
	Loaded drive/Othercomputers/MacBookPro/lego val
	Changed 60 items out of 72 in array of shape (6, 3, 4)
		From (1, 0, 0) to (5, 2, 3)
Generating rays: 100% 6/6 [00:01<00:00,  5.69pose/s]
Creating datasets...
	Computing view dirs for train...
	Creating train dataset with rays (torch.Size([640000, 9])) and images (torch.Size([640000, 3])) - shuffle True
	Computing view dirs for val...
	Creating val dataset with rays (torch.Si

# Voxelised Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/voxelised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/voxelised_radiancemap.conf

Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1551360000 bytes == 0x98b8000 @  0x7fa765f27001 0x7fa6f57dc1af 0x7fa6f5832c23 0x7fa6f5833a87 0x7fa6f58d5823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fa765b22c87 0x5b621a
Loading train - 1 images...
Fileposes:  drive/Othercomputers/MacBookPro/microphone/poses_bounds_train.npy
	from train_1
	Loaded image data (800, 800, 3, 1) [ 800.          800.         1010.71837593]
	Loaded drive/Othercomputers/MacBookPro/microphone train
	Changed 12 items out of 1212 in array of shape (101, 3, 4)
		From (0, 0, 0) to (0, 2, 3)
Loading val - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/microphone/poses_bounds_val.npy
	from val_1
tcmalloc: large alloc 1536000000 bytes == 0xc1cba000 @  0x7fa765f251e7 0x7fa6f57dc0ce 0x7fa6f5832cf5 0x7fa6f58db86d 0x7fa6f58dc17f 0x7fa6f58dc2d0 0x4bc4ab 0x7f

# Clusterised Radiance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf

Using cuda
dataset to:  cpu
['val', 'train']
tcmalloc: large alloc 3072000000 bytes == 0x95b4000 @  0x7f1b9f86e001 0x7f1b2f1231af 0x7f1b2f179c23 0x7f1b2f17aa87 0x7f1b2f21c823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f1b9f469c87 0x5b621a
Loading val - 100 poses and images (800x800)...
	Changed 1153 items out of 2400 in array of shape (200, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading train - 100 poses and images (800x800)...
	Changed 1151 items out of 2400 in array of shape (200, 3, 4)
		From (100, 0, 0) to (199, 2, 3)
Generating rays: 100% 200/200 [00:37<00:00,  5.39pose/s]
tcmalloc: large alloc 6144000000 bytes == 0x7f18fe0d0000 @  0x7f1b9f84eb6b 0x7f1b9f86e379 0x7f1b2fe0bd57 0x7f1b2fdf9bc3 0x7f1b59d046af 0x7f1b59d05020 0x7f1b59d05074 0x7f1b59d051bf 0x7f1b5aa8c82b 0x7f1b5aaefd42 0x7f1b5a22fe37 0x7f1b5aa9589e 0x7f1b5aa95923 0x7f1b5a5a6565 0x7f1b5a242531 0

In [ ]:
for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

Using cuda
dataset to:  cpu
['val', 'train', 'relighting']
tcmalloc: large alloc 3102720000 bytes == 0x9950000 @  0x7f1126b96001 0x7f10b644b1af 0x7f10b64a1c23 0x7f10b64a2a87 0x7f10b6544823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f1126791c87 0x5b621a
Loading val - 2 poses and images (800x800)...
	Changed 23 items out of 2424 in array of shape (202, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses and images (800x800)...
	Changed 1151 items out of 2424 in array of shape (202, 3, 4)
		From (2, 0, 0) to (101, 2, 3)
Loading relighting - 100 poses and images (800x800)...
	Changed 1140 items out of 2424 in array of shape (202, 3, 4)
		From (102, 0, 0) to (201, 2, 3)
Generating rays: 100% 202/202 [00:36<00:00,  5.47pose/s]
tcmalloc: large alloc 6205440000 bytes == 0x7f0e7a3f4000 @  0x7f1126b76b6b 0x7f1126b96379 0x7f10b7133d57 0x7f10b7121bc3 0x7f10e1

# Reflectance Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf

In [ ]:
for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

for (kmeans_tol, num_clusters) in [(2e-00, 512), (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
    ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'test']
Traceback (most recent call last):
  File "drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py", line 119, in <module>
    dataset = data.NeRFDataset(args)
  File "drive/Othercomputers/MacBookPro/utils/data.py", line 437, in __init__
    load_light=args.load_light)
  File "drive/Othercomputers/MacBookPro/utils/data.py", line 667, in load_synthetic
    imgs_size, num_images = get_images_size(basedir, subdirs, factor=factor)
  File "drive/Othercomputers/MacBookPro/utils/data.py", line 125, in get_images_size
    files_list = [f for f in os.listdir(os.path.join(basedir, subdir)) 
KeyboardInte

# Reflectance Linear Mapping with Spherical Harmonics Encoding

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf

Traceback (most recent call last):
  File "drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py", line 6, in <module>
    import open3d as o3d
  File "/usr/local/lib/python3.7/dist-packages/open3d/__init__.py", line 69, in <module>
    from open3d.cuda.pybind import (camera, data, geometry, io,
ImportError: KeyboardInterrupt: 


In [ ]:
for scene in ["lego", "microphone", "drums"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}_light/{scene}_aligned.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}_light"
    out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/reflectance_{scene}_relighting_sphharm"
    checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/reflectance_{scene}_perfectmesh"
    
    for (kmeans_tol, num_clusters) in [(2e-00, 512)]:#, (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm_relighting.conf --val_images=2 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

    '''for (kmeans_tol, num_clusters) in [(2e-00, 512)]:#, (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm_relighting.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path'''

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'relighting']
tcmalloc: large alloc 1582080000 bytes == 0x8ed2000 @  0x7f906cb25001 0x7f8ffc39a1af 0x7f8ffc3f0c23 0x7f8ffc3f1a87 0x7f8ffc493823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f906c720c87 0x5b621a
Loading val - 2 poses, images (800x800) and lights...
	Changed 23 items out of 1236 in array of shape (103, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 1 poses, images (800x800) and lights...
	Changed 12 items out of 1236 in array of shape (103, 3, 4)
		From (2, 0, 0) t

In [ ]:
for scene in ["lego", "microphone", "drums"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}_light/{scene}_aligned.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}_light"
    out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/reflectance_{scene}_perfectmesh"
    checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/reflectance_{scene}_perfectmesh"
    
    for (kmeans_tol, num_clusters) in [(2e-00, 512)]:#, (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

    for (kmeans_tol, num_clusters) in [(2e-00, 512)]:#, (2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train']
tcmalloc: large alloc 1566720000 bytes == 0x8fbc000 @  0x7fa419282001 0x7fa3a8af71af 0x7fa3a8b4dc23 0x7fa3a8b4ea87 0x7fa3a8bf0823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fa418e7dc87 0x5b621a
Loading val - 2 poses, images (800x800) and lights...
	Changed 23 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1151 items out of 1224 in array of shape (102, 3, 4)
		From (2, 0, 0) to (101, 2,

# Enhanced Reflectance Network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/enhanced_reflectance_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/enhanced_reflectance_network.conf

Using cuda
dataset to:  cpu
['val', 'train', 'test']
tcmalloc: large alloc 1689600000 bytes == 0x8684000 @  0x7fcfa5b02001 0x7fcf353b71af 0x7fcf3540dc23 0x7fcf3540ea87 0x7fcf354b0823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fcfa56fdc87 0x5b621a
Loading val - 10 poses, images (800x800) and lights...
	Changed 113 items out of 1320 in array of shape (110, 3, 4)
		From (0, 0, 0) to (9, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1320 in array of shape (110, 3, 4)
		From (10, 0, 0) to (109, 2, 3)
Generating rays: 100% 110/110 [00:20<00:00,  5.47pose/s]
tcmalloc: large alloc 3379200000 bytes == 0x7fcddf038000 @  0x7fcfa5ae2b6b 0x7fcfa5b02379 0x7fcf3609fd57 0x7fcf3608dbc3 0x7fcf5ff986af 0x7fcf5ff99020 0x7fcf5ff99074 0x7fcf5ff991bf 0x7fcf60d2082b 0x7fcf60d83d42 0x7fcf604c3e37 0x7fcf60d2989e 0x7fcf60d29923 0x7fcf6083a

# Ablation Studies

## No normals

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf

path ['/content/drive/Othercomputers/MacBookPro/Rendering/ablations', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '../', 'drive/Othercomputers/MacBookPro/', 'drive/Othercomputers/MacBookPro/Rendering/']
Traceback (most recent call last):
  File "drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py", line 98, in <module>
    import utils.data as data
  File "drive/Othercomputers/MacBookPro/utils/data.py", line 9, in <module>
    import cv2, imageio
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
Key

In [3]:
for scene in ["drums"]:#, "lego", "microphone"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}/{scene}_aligned2colmap.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}"
    out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/clusterised_radiance_nonormals_{scene}"
    checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/clusterised_radiance_nonormals_{scene}"
    
    for (kmeans_tol, num_clusters) in [(5e-01, 64)]:#[(2e-00, 125), (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path
        ! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_nonormals.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

path ['/content/drive/Othercomputers/MacBookPro/Rendering/ablations', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '../', 'drive/Othercomputers/MacBookPro/', 'drive/Othercomputers/MacBookPro/Rendering/']
Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x8742000 @  0x7f8c6ee60001 0x7f8bfe7151af 0x7f8bfe76bc23 0x7f8bfe76ca87 0x7f8bfe80e823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f8c6ea5bc87 0x5b621a
Loading train - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_train.npy
	from train_1
tcmalloc: large alloc 1536000000 bytes == 0xc19ea000 @  0x7f8c6ee5e1e7 0x7f8bfe7150ce 0x7f8bfe76bcf5 0x7f8bfe81486d 0x7f8bfe81517f 0x7f8bfe8152d0 0x4bc4ab 0x7f8bfe756944 0x59

## No view dirs

In [4]:
for scene in ["drums"]:#, "lego", "microphone"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}/{scene}_aligned2colmap.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}"
    out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/clusterised_radiance_noviewdirs_{scene}"
    checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/clusterised_radiance_noviewdirs_{scene}"
    
    for (kmeans_tol, num_clusters) in [(5e-01, 64)]:#, (5e-01, 64), (1e-01, 8)]:
        ! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_noviewdirs.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=2 --train_images=100 --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path
        ! python3 drive/Othercomputers/MacBookPro/Rendering/ablations/clusterised_radiance_noviewdirs.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --num_clusters=$num_clusters --kmeans_tol=$kmeans_tol --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

path ['/content/drive/Othercomputers/MacBookPro/Rendering/ablations', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '../', 'drive/Othercomputers/MacBookPro/', 'drive/Othercomputers/MacBookPro/Rendering/']
Using cuda
only eval? False
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x84fc000 @  0x7f3901455001 0x7f3890d0a1af 0x7f3890d60c23 0x7f3890d61a87 0x7f3890e03823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f3901050c87 0x5b621a
Loading train - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_train.npy
	from train_1
tcmalloc: large alloc 1536000000 bytes == 0xc17a4000 @  0x7f39014531e7 0x7f3890d0a0ce 0x7f3890d60cf5 0x7f3890e0986d 0x7f3890e0a17f 0x7f3890e0a2d0 0x4bc4ab 0x

## No Positional Encoding & 3 freq. Pos. Enc

In [6]:
for scene in ["drums"]:#, "lego", "microphone"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}/{scene}_aligned2colmap.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}"
        
    for encoding_freqs in [6]:
        out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/clusterised_radiance_{scene}/{encoding_freqs}freqs"
        checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/clusterised_radiance_{scene}/{encoding_freqs}freqs"
        
        !python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=2 --train_images=100 --encoding_freqs=$encoding_freqs --out_path=$out_path --checkpoint_path=$checkpoint_path --dataset_path=$dataset_path --mesh_path=$mesh_path
        !python3 drive/Othercomputers/MacBookPro/Rendering/clusterised_radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/clusterised_radiancemap.conf --val_images=100 --train_images=1 --only_eval --encoding_freqs=$encoding_freqs --out_path=$out_path --checkpoint_path=$checkpoint_path --dataset_path=$dataset_path --mesh_path=$mesh_path

Using cuda
dataset to:  cpu
['train', 'val', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x838a000 @  0x7fed7e196001 0x7fed0da4b1af 0x7fed0daa1c23 0x7fed0daa2a87 0x7fed0db44823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fed7dd91c87 0x5b621a
Loading train - 100 images...
Fileposes:  drive/Othercomputers/MacBookPro/drums/poses_bounds_train.npy
	from train_1
tcmalloc: large alloc 1536000000 bytes == 0xc1632000 @  0x7fed7e1941e7 0x7fed0da4b0ce 0x7fed0daa1cf5 0x7fed0db4a86d 0x7fed0db4b17f 0x7fed0db4b2d0 0x4bc4ab 0x7fed0da8c944 0x59371f 0x515244 0x549576 0x593fce 0x548ae9 0x5127f1 0x549e0e 0x4bcb19 0x7fed0da8c944 0x59371f 0x515244 0x549576 0x593fce 0x548ae9 0x51566f 0x549e0e 0x593fce 0x548ae9 0x5127f1 0x549576 0x593fce 0x548ae9 0x5127f1
	Loaded image data (800, 800, 3, 100) [ 800.          800.         1238.06948234]
	Loaded drive/Othercomputers/MacBookPro/

## No Spherical Harmonics, 1, 2, 3, 4, 5 degree views

In [6]:
for scene in ["drums", "lego", "microphone"]:    
    mesh_path = f"drive/Othercomputers/MacBookPro/{scene}_light/meshed-poisson_aligned.ply"
    dataset_path = f"drive/Othercomputers/MacBookPro/{scene}_light"
    
    for deg_view in [-1]:
        out_path = f"drive/Othercomputers/MacBookPro/Rendering/out/reflectance_{scene}_light_sphharm/{deg_view}degrees"
        checkpoint_path = f"drive/Othercomputers/MacBookPro/Rendering/checkpoints/reflectance_{scene}_light_sphharm/{deg_view}degrees"
    
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=2 --train_images=100 --deg_view=$deg_view --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path
        ! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_sphharm.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_sphharm.conf --val_images=100 --train_images=1 --deg_view=$deg_view --only_eval --mesh_path=$mesh_path --dataset_path=$dataset_path --out_path=$out_path --checkpoint_path=$checkpoint_path

['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['val', 'train', 'test']
tcmalloc: large alloc 1566720000 bytes == 0x8d50000 @  0x7fa416bb5001 0x7fa3a642a1af 0x7fa3a6480c23 0x7fa3a6481a87 0x7fa3a6523823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fa4167b0c87 0x5b621a
Loading val - 2 poses, images (800x800) and lights...
	Changed 22 items out of 1224 in array of shape (102, 3, 4)
		From (0, 0, 0) to (1, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1224 in array of shape (102, 3, 4)
		From (2, 0, 0) to 

# Residual Reflectance

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/resref_colab.conf

# Reflectance Mapping Network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Cluster selector network

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_clusterized_network.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Linear Mapping + Residual MLP

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/mapping_residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_net_colab.conf

# Autodecoder

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_autodecoder.py -c drive/Othercomputers/MacBookPro/Rendering/configs/autodecoder_colab.conf

Using cuda
['val', 'train', 'test']
tcmalloc: large alloc 1612800000 bytes == 0x9a6a000 @  0x7f8b4657d001 0x7f8ad5e321af 0x7f8ad5e88c23 0x7f8ad5e89a87 0x7f8ad5f2b823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86 0x594a96 0x548cc1 0x51566f 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f8b46178c87 0x5b621a
Loading val - 5 poses, images (800x800) and lights...
	Changed 56 items out of 1260 in array of shape (105, 3, 4)
		From (0, 0, 0) to (4, 2, 3)
Loading train - 100 poses, images (800x800) and lights...
	Changed 1143 items out of 1260 in array of shape (105, 3, 4)
		From (5, 0, 0) to (104, 2, 3)
Generating rays: 100% 105/105 [00:20<00:00,  5.05pose/s]
tcmalloc: large alloc 3225600000 bytes == 0x12a0ac000 @  0x7f8b4655db6b 0x7f8b4657d379 0x7f8ad6b1ad57 0x7f8ad6b08bc3 0x7f8b00a136af 0x7f8b00a14020 0x7f8b00a14074 0x7f8b00a141bf 0x7f8b0179b82b 0x7f8b017fed42 0x7f8b00f3ee37 0x7f8b017a489e 0x7f8b017a4923 0x7f8b012b5565 0x7f8b00f51531 0x7f

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_autoencoder.py -c drive/Othercomputers/MacBookPro/Rendering/configs/autodecoder_colab.conf

In [ ]:
import torch
t1 = torch.tensor([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [7, 8, 9]])

unique, inverse = torch.unique(t1, sorted=True, return_inverse=True, dim=0)
perm = torch.arange(inverse.size(0), dtype=inverse.dtype, device=inverse.device)
inverse, perm = inverse.flip([0]), perm.flip([0])
print(unique)
print(inverse)
perm = inverse.new_empty(unique.size(0)).scatter_(0, inverse, perm)
print(perm)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 1, 0, 1, 0])
tensor([0, 1, 4])


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 2])
x.index_fill_(0, index, -1)

cluster_ids = []

tensor([[-1.5066, -0.0317,  0.7404, -0.8176],
        [ 1.2103, -1.2459, -0.9263,  1.2217],
        [-0.0228, -1.3056,  0.7262,  0.2709],
        [-0.6637, -2.1896, -0.3487, -1.2596]])
tensor([[False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True]])
tensor([2, 3, 2, 2])


In [ ]:
X = torch.tensor([[1., 2., 3.], [4., 5., 6.], [1, 2, 3], [4, 5, 6], [7, 8, 9]])
cluster_ids = torch.arange(0, end=5)
cluster_ids = cluster_ids[torch.randperm(cluster_ids.shape[0])]

values = torch.rand((5, 10))
print(values)
col_indices = torch.stack([cluster_ids, cluster_ids+1, cluster_ids+2], dim=0)
print(col_indices)
row_indices = torch.arange(5)
print(values[row_indices, col_indices].T)
print(values[row_indices, col_indices].T.shape)


tensor([[9.2120e-01, 6.5819e-01, 4.7914e-01, 1.4890e-01, 5.2660e-01, 6.3940e-01,
         9.8772e-01, 5.9303e-01, 7.0703e-01, 8.4739e-01],
        [8.5110e-01, 4.0239e-04, 2.8202e-01, 9.1530e-01, 1.8869e-01, 4.2283e-01,
         2.7864e-01, 1.2488e-01, 4.7079e-01, 2.5965e-01],
        [6.6420e-01, 7.4319e-01, 7.1035e-01, 9.8808e-01, 5.7236e-01, 3.9414e-01,
         9.3400e-05, 8.8030e-01, 5.3952e-01, 1.6256e-01],
        [9.9138e-01, 9.0262e-01, 4.6338e-01, 7.3467e-01, 6.1284e-01, 4.9806e-01,
         5.6239e-01, 3.8199e-01, 4.3856e-01, 4.6844e-01],
        [9.2781e-01, 5.1247e-01, 4.5681e-01, 5.4670e-01, 2.5513e-01, 3.3994e-01,
         3.1610e-01, 4.8427e-01, 7.8315e-01, 8.5255e-02]])
tensor([[2, 0, 1, 4, 3],
        [3, 1, 2, 5, 4],
        [4, 2, 3, 6, 5]])
tensor([[4.7914e-01, 1.4890e-01, 5.2660e-01],
        [8.5110e-01, 4.0239e-04, 2.8202e-01],
        [7.4319e-01, 7.1035e-01, 9.8808e-01],
        [6.1284e-01, 4.9806e-01, 5.6239e-01],
        [5.4670e-01, 2.5513e-01, 3.3994e-01]

In [ ]:
import torch
cluster_ids = torch.arange(0,10)

X = torch.rand((10, 3))

def get_x2cluster(X, cluster_ids, num_clusters):
    indices = torch.stack([torch.arange(0,cluster_ids.shape[0]), cluster_ids])
    clusters = torch.sparse_coo_tensor(indices, torch.ones((cluster_ids.shape[0],)), (cluster_ids.shape[0], num_clusters)).to_dense()
    print(clusters.shape)
    x2cluster = torch.linalg.pinv(X) @ clusters  
    print(x2cluster.shape)
    return x2cluster

get_x2cluster(X, cluster_ids, 15)

torch.Size([10, 15])
torch.Size([3, 15])


tensor([[ 0.5149, -0.2283,  0.1728,  0.2384, -0.1754, -0.0055,  0.0579,  0.5413,
         -0.4568, -0.0634,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.4487, -0.1163,  0.1923, -0.0186,  0.7851, -0.2504,  0.1239, -0.3273,
          0.5835, -0.1806,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.1145,  0.5559, -0.1027, -0.0907, -0.4760,  0.4144,  0.0624, -0.0064,
          0.0639,  0.3303,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])