In [2]:
from google.colab import drive
drive.mount('/content/drive')
! pip install configargparse
! pip install wandb
! pip install open3d

Mounted at /content/drive
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.8 MB 4.0 MB/s 
     |████████████████████████████████| 181 kB 60.4 MB/s 
     |████████████████████████████████| 146 kB 51.1 MB/s 
     |████████████████████████████████| 63 kB 1.9 MB/s 
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8806 sha256=a11cb0d16e5c19ad7fb7a9746825f384bf2a238bd0bd9fd775c6a432e5954161
  Stored in directory: /root/.cache/pip/wheels/3e/31/09/fa59cef12cdcfecc627b3d24273699f390e71828921b2cbba2
Successfully built pathtools
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 408.6 MB 31 kB/s 
     |████████████████████████████████| 8.8 MB 51.3 MB/s 
     |████████████████████████████████| 3

## Run NeRF
WandB apikey: 209f6ac4375563c3d09904b96206a2f5f1d75c24


In [ ]:
! python3 drive/Othercomputers/MacBookPro/NeRF/main.py -c drive/Othercomputers/MacBookPro/NeRF/configs/lego_llff_colab.conf

usage: main.py [-h] [-c CONFIG] [--mesh MESH] [--dataset_path DATASET_PATH]
               [--out_path OUT_PATH]
               [--dataset_type {synthetic,llff,tiny,meshroom,colmap}]
               [--factor FACTOR] [--batch_size BATCH_SIZE] [--shuffle SHUFFLE]
               [--N_samples N_SAMPLES] [--D_c D_C] [--W_c W_C] [--N_f N_F]
               [--lrate LRATE] [--lrate_decay LRATE_DECAY] [--N_iters N_ITERS]
               [--near NEAR] [--far FAR] [--raw_noise_std RAW_NOISE_STD]
               [--dataset_to_gpu] [--colab] [--colab_path COLAB_PATH] [--test]
main.py: error: argument --batch_size: invalid int value: '1024*8'


In [ ]:
! python3 drive/Othercomputers/MacBookPro/nerf-pytorch/run_nerf.py --config drive/Othercomputers/MacBookPro/nerf-pytorch/configs/orchids.txt

## Run Ray tracing a mesh

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Ray-tracing_mesh/ray_tracing_mesh.py -c drive/Othercomputers/MacBookPro/Ray-tracing_mesh/configs/lego_llff.conf

## Surface rendering

In [ ]:
import torch
print(torch.__version__)
! pip3 show torch

1.11.0+cu113
Name: torch
Version: 1.11.0+cu113
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.7/dist-packages
Requires: typing-extensions
Required-by: torchvision, torchtext, torchaudio, fastai


In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/surface_rendering.py -c drive/Othercomputers/MacBookPro/Rendering/configs/surfrend_colab.conf

python3: can't open file 'drive/Othercomputers/MacBookPro/NeRF/surface_rendering.py': [Errno 2] No such file or directory


## Linear Mapping

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/linear_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/linearmap_colab.conf

Using cuda
dataset to:  cpu
['train', 'val']
Loading train - 100 images...
	from train_8
	Loaded image data (100, 100, 3, 100) [100.         100.         137.88755316]
	Loaded drive/Othercomputers/MacBookPro/lego_llff train
	Changed 1200 items out of 1260 in array of shape (105, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading val - 5 images...
	from val_8
	Loaded image data (100, 100, 3, 5) [100.         100.         137.88755316]
	Loaded drive/Othercomputers/MacBookPro/lego_llff val
	Changed 60 items out of 1260 in array of shape (105, 3, 4)
		From (100, 0, 0) to (104, 2, 3)
Generating rays: 100% 105/105 [00:00<00:00, 348.37pose/s]
Creating datasets...
	Computing view dirs for train...
	Creating train dataset with rays (torch.Size([1000000, 9])) and images (torch.Size([1000000, 3])) - shuffle True
	Computing view dirs for val...
	Creating val dataset with rays (torch.Size([50000, 9])) and images (torch.Size([50000, 3])) - shuffle True
Datasets created successfully

Reading PLY file: driv

# Residual Reflectance

In [ ]:
import torch
values = torch.tensor([[1.2, 2.1, 3.2], [1.4, 2.2, 3.1], [1.5, 2.2, 3.1]])
samples = torch.tensor([[2.1, 0.2, 1.3], [2.9,3.2,5.3], [.12, 12.2, 2.4]])
samplesA = samples.unsqueeze(1)
samplesB = samples.unsqueeze(0)
dif = samplesA - samplesB
print(dif)
print(dif.shape)
dist = torch.norm(dif, dim=-1)
print(dist)
print(dist > 6)
mask = torch.triu(dist > 6, diagonal=1)
indices = torch.argwhere(mask)
print(indices)
print(indices[:,0])
print(values[indices[:,0]])
print(values[indices[:,1]])
loss = values[indices[:,0]] - values[indices[:,1]]
print(loss)
loss_fn = torch.nn.MSELoss(reduction='none')
print(loss_fn(values[indices[:,0]], values[indices[:,1]]))
loss_fn = torch.nn.MSELoss(reduction='sum')
print(loss_fn(values[indices[:,0]], values[indices[:,1]]))
loss_fn = torch.nn.MSELoss(reduction='mean')
print(loss_fn(values[indices[:,0]], values[indices[:,1]]))

tensor([[[  0.0000,   0.0000,   0.0000],
         [ -0.8000,  -3.0000,  -4.0000],
         [  1.9800, -12.0000,  -1.1000]],

        [[  0.8000,   3.0000,   4.0000],
         [  0.0000,   0.0000,   0.0000],
         [  2.7800,  -9.0000,   2.9000]],

        [[ -1.9800,  12.0000,   1.1000],
         [ -2.7800,   9.0000,  -2.9000],
         [  0.0000,   0.0000,   0.0000]]])
torch.Size([3, 3, 3])
tensor([[ 0.0000,  5.0636, 12.2119],
        [ 5.0636,  0.0000,  9.8559],
        [12.2119,  9.8559,  0.0000]])
tensor([[False, False,  True],
        [False, False,  True],
        [ True,  True, False]])
tensor([[0, 2],
        [1, 2]])
tensor([0, 1])
tensor([[1.2000, 2.1000, 3.2000],
        [1.4000, 2.2000, 3.1000]])
tensor([[1.5000, 2.2000, 3.1000],
        [1.5000, 2.2000, 3.1000]])
tensor([[-0.3000, -0.1000,  0.1000],
        [-0.1000,  0.0000,  0.0000]])
tensor([[0.0900, 0.0100, 0.0100],
        [0.0100, 0.0000, 0.0000]])
tensor(0.1200)
tensor(0.0200)


In [4]:
! python3 drive/Othercomputers/MacBookPro/Rendering/residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/resref_colab.conf

Using cuda
dataset to:  cpu
['train', 'val']
Loading train - 100 images...
	from train_8
	Loaded image data (100, 100, 3, 100) [100.         100.         137.88755316]
	Loaded drive/Othercomputers/MacBookPro/lego_llff train
	Changed 1200 items out of 2400 in array of shape (200, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading val - 100 images...
	from val_8
	Loaded image data (100, 100, 3, 100) [100.         100.         137.88755316]
	Loaded drive/Othercomputers/MacBookPro/lego_llff val
	Changed 1200 items out of 2400 in array of shape (200, 3, 4)
		From (100, 0, 0) to (199, 2, 3)
Generating rays: 100% 200/200 [00:00<00:00, 276.26pose/s]
Creating datasets...
	Computing view dirs for train...
	Creating train dataset with rays (torch.Size([1000000, 9])) and images (torch.Size([1000000, 3])) - shuffle True
	Computing view dirs for val...
	Creating val dataset with rays (torch.Size([1000000, 9])) and images (torch.Size([1000000, 3])) - shuffle True
Datasets created successfully

Reading PLY 