In [39]:
from google.colab import drive
drive.mount('/content/drive')
! pip install configargparse
! pip install wandb
! pip install open3d

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Run NeRF
WandB apikey: 209f6ac4375563c3d09904b96206a2f5f1d75c24


In [ ]:
! python3 drive/Othercomputers/MacBookPro/NeRF/main.py -c drive/Othercomputers/MacBookPro/NeRF/configs/lego_llff_colab.conf

usage: main.py [-h] [-c CONFIG] [--mesh MESH] [--dataset_path DATASET_PATH]
               [--out_path OUT_PATH]
               [--dataset_type {synthetic,llff,tiny,meshroom,colmap}]
               [--factor FACTOR] [--batch_size BATCH_SIZE] [--shuffle SHUFFLE]
               [--N_samples N_SAMPLES] [--D_c D_C] [--W_c W_C] [--N_f N_F]
               [--lrate LRATE] [--lrate_decay LRATE_DECAY] [--N_iters N_ITERS]
               [--near NEAR] [--far FAR] [--raw_noise_std RAW_NOISE_STD]
               [--dataset_to_gpu] [--colab] [--colab_path COLAB_PATH] [--test]
main.py: error: argument --batch_size: invalid int value: '1024*8'


In [ ]:
! python3 drive/Othercomputers/MacBookPro/nerf-pytorch/run_nerf.py --config drive/Othercomputers/MacBookPro/nerf-pytorch/configs/orchids.txt

## Run Ray tracing a mesh

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Ray-tracing_mesh/ray_tracing_mesh.py -c drive/Othercomputers/MacBookPro/Ray-tracing_mesh/configs/lego_llff.conf

## Surface rendering

In [ ]:
import torch
print(torch.__version__)
! pip3 show torch

1.11.0+cu113
Name: torch
Version: 1.11.0+cu113
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.7/dist-packages
Requires: typing-extensions
Required-by: torchvision, torchtext, torchaudio, fastai


In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/surface_rendering.py -c drive/Othercomputers/MacBookPro/Rendering/configs/surfrend_colab.conf

python3: can't open file 'drive/Othercomputers/MacBookPro/NeRF/surface_rendering.py': [Errno 2] No such file or directory


## Radiance Linear Mapping

In [16]:
! python3 drive/Othercomputers/MacBookPro/Rendering/radiance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/radiancemap_colab.conf

drive/Othercomputers/MacBookPro/utils/utils.py:20: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(old_arr.shape == new_arr.shape, "The 2 arrays have different shape, cannot find the differences.")
Using cuda
dataset to:  cpu
['train', 'val']
tcmalloc: large alloc 1612800000 bytes == 0x8a20000 @  0x7f5de69aa001 0x7f5d762981af 0x7f5d762eec23 0x7f5d762efa87 0x7f5d76391823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x549576 0x4bca8a 0x532b86 0x594a96 0x548cc1 0x5127f1 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f5de65a5c87 0x5b621a
Loading train - 100 poses and images (800x800)...
	Changed 1150 items out of 1260 in array of shape (105, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading val - 5 poses and images (800x800)...
	Changed 59 items out of 1260 in array of shape (105, 3, 4)
		From (100, 0, 0) to (104, 2, 3)
Focal length: 785.0441767523804
Generating rays: 100% 105/105 [00:19<00:00,  5.43pose/s]
tcmalloc: large alloc

# Residual Reflectance

In [ ]:
! python3 drive/Othercomputers/MacBookPro/Rendering/residual_reflectance.py -c drive/Othercomputers/MacBookPro/Rendering/configs/resref_colab.conf

Using cuda
dataset to:  cpu
['train', 'val']
tcmalloc: large alloc 1612800000 bytes == 0x8a3e000 @  0x7fcb49698001 0x7fcad8f861af 0x7fcad8fdcc23 0x7fcad8fdda87 0x7fcad907f823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x549576 0x4bca8a 0x532b86 0x594a96 0x548cc1 0x5127f1 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fcb49293c87 0x5b621a
Loading train - 100 poses and images (800x800)...
	Changed 1150 items out of 1260 in array of shape (105, 3, 4)
		From (0, 0, 0) to (99, 2, 3)
Loading val - 5 poses and images (800x800)...
	Changed 59 items out of 1260 in array of shape (105, 3, 4)
		From (100, 0, 0) to (104, 2, 3)
Focal length: 785.0441767523804
Generating rays: 100% 105/105 [00:18<00:00,  5.59pose/s]
tcmalloc: large alloc 3225600000 bytes == 0x129092000 @  0x7fcb49678b6b 0x7fcb49698379 0x7fcad9c6ed57 0x7fcad9c5cbc3 0x7fcb03b5239f 0x7fcb03b52d10 0x7fcb03b52d64 0x7fcb03b52eaf 0x7fcb048d853b 0x7fcb0493ba52 0x7fcb0407d047 0x7fcb048e15ae 0x7fcb048e16

# Reflectance Linear Mapping

In [19]:
! python3 drive/Othercomputers/MacBookPro/Rendering/reflectance_mapping.py -c drive/Othercomputers/MacBookPro/Rendering/configs/reflectancemap_colab.conf

drive/Othercomputers/MacBookPro/utils/utils.py:20: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(old_arr.shape == new_arr.shape, "The 2 arrays have different shape, cannot find the differences.")
['/content/drive/Othercomputers/MacBookPro/Rendering', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '../', 'drive/Othercomputers/MacBookPro/', '../']
Using cuda
dataset to:  cpu
['train', 'val']
tcmalloc: large alloc 1612800000 bytes == 0x8dc0000 @  0x7fa014f10001 0x7f9fa47fe1af 0x7f9fa4854c23 0x7f9fa4855a87 0x7f9fa48f7823 0x5936cc 0x548c51 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x549576 0x4bca8a 0x532b86 0x594a96 0x548cc1 0x5127f1 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7fa014b0bc87 0x5b621a
Loading train - 100 poses, images (800x800) and lights.

In [ ]:
import torch
t1 = torch.tensor([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [7, 8, 9]])

unique, inverse = torch.unique(t1, sorted=True, return_inverse=True, dim=0)
perm = torch.arange(inverse.size(0), dtype=inverse.dtype, device=inverse.device)
inverse, perm = inverse.flip([0]), perm.flip([0])
print(unique)
print(inverse)
perm = inverse.new_empty(unique.size(0)).scatter_(0, inverse, perm)
print(perm)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 1, 0, 1, 0])
tensor([0, 1, 4])


In [ ]:
34837302 > 1e07

True